#!/usr/bin/env ruby
require "dotenv/load"

rum :"brutalismbot/mail" do
  tag %x(git describe --tags --always).strip

  env :AWS_ACCESS_KEY_ID
  env :AWS_SECRET_ACCESS_KEY
  env :AWS_DEFAULT_REGION
  env :RUNTIME => "ruby2.5"
  env :TF_VAR_destinations
  env :TF_VAR_release => tag

  stage :build
  stage :plan => :build

  artifact "lambda.zip" => :build

  desc "Apply infrastructure"
  run :apply => :plan

  default %w[lambda.zip plan]
end
